version: '3'
volumes:
  node_modules:
services : 
  vue:
    image : louneah/vue-typescript-bootstrap
    container_name : vue
    volumes :
      - ./project:/project
      - node_modules:/project/node_modules
    ports : 
      - 8080:8080
    environment:
      - CHOKIDAR_USEPOLLING=true
    command : bash -c "npm install && npm run serve"
      